version: '3.2'
services:
    analytics:
        environment:
            - LEARNING_DASH_BOARD_PATH='/var/bigbluebutton/learning-dashboard/'
        container_name: analytics-api
        volumes:
            - /var/bigbluebutton/learning-dashboard/:/usr/src/app/learning-dashboard
        image: analytics:v1
        ports:
            - "3006:8080"
